name: second workflow
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{toJson(github)}}"
